p8105_hw3_fw2394
================
Fang Wang
2024-10-12

# Load necessary libraries

``` r
library (tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   3.5.1     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.3     ✔ tidyr     1.3.1
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library (dplyr)
library (patchwork)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp =.6,
  out.width = "90%"
)

theme_set (theme_bw() + theme (
    legend.position =  "bottom"
  ))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_color_discrete = scale_color_viridis_d()
scale_fill_discrete = scale_fill_viridis_d()
```

# Problem 1

## Load data:

``` r
library(p8105.datasets)
data("ny_noaa")
```

*The ny_noaa dataset contains 30 years of weather forecast data for New
York State, collected from various NOAA weather stations. The dataset is
structured with each row representing a single observation at a specific
station and date, and columns corresponding to the various recorded
variables. It has 2595176 observations and 7 variables. The variables
includes “id” (weather station ID), “date” (date of observation), “prcp”
(precipitation), “snow” (snowfall), “snwd” (snow depth), “tmax” (maximum
temperature) and “tmin” (minimum temperature).*

## Check missing data for each variable:

``` r
ny_noaa |> 
    summarise(pro_prcp = mean(is.na(prcp)))
```

    ## # A tibble: 1 × 1
    ##   pro_prcp
    ##      <dbl>
    ## 1   0.0562

``` r
ny_noaa |> 
    summarise(pro_snow = mean(is.na(snow)))
```

    ## # A tibble: 1 × 1
    ##   pro_snow
    ##      <dbl>
    ## 1    0.147

``` r
ny_noaa |> 
    summarise(pro_snwd = mean(is.na(snwd)))
```

    ## # A tibble: 1 × 1
    ##   pro_snwd
    ##      <dbl>
    ## 1    0.228

``` r
ny_noaa |> 
    summarise(pro_tmax = mean(is.na(tmax)))
```

    ## # A tibble: 1 × 1
    ##   pro_tmax
    ##      <dbl>
    ## 1    0.437

``` r
ny_noaa |> 
    summarise(pro_tmin = mean(is.na(tmin)))
```

    ## # A tibble: 1 × 1
    ##   pro_tmin
    ##      <dbl>
    ## 1    0.437

*In prcp (precipitation) variable, approximately 6% of values are
missing. In snow (snowfall), around 15% of values are missing. In snwd
(snow depth) variable, about 23% of values are missing. In tmax (maximum
temperature), approximately 44% of values are missing. In tmin (minimum
temperature), about 44% of values are missing. These figures indicate
that while some variables (e.g., precipitation) have relatively low
levels of missing data, others (e.g., maximum temperature and minimum
temperature) have substantial gaps. This missing data may affect
analyses, particularly those involving temperature.*

## Create separate variables for year, month, and day:

``` r
ny_noaa = ny_noaa |> 
separate(date, into = c("year", "month", "day"), sep = "-")
```

## Convert the units of precipitation (tenths of mm), maximum temperature (tenths of degrees C) and minimum temperature (tenths of degrees C) into precipitation in mm, maximum temperature and minimum temperatuere in degrees C.

``` r
ny_noaa = ny_noaa |>
  mutate (
    prcp = ifelse(!is.na(prcp), as.numeric(prcp)/10, NA),
    tmax = ifelse(!is.na(tmax), as.numeric(tmax)/10, NA),
    tmin = ifelse(!is.na(tmin), as.numeric(tmin)/10, NA)  
    )
```

## Check the most commonly observed values for snowfall:

``` r
ny_noaa |> 
  ggplot (aes(x=snow)) + 
  geom_histogram()
```

    ## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.

    ## Warning: Removed 381221 rows containing non-finite outside the scale range
    ## (`stat_bin()`).

<img src="p8105_hw3_fw2394_files/figure-gfm/snow-1.png" width="90%" />

``` r
ggsave("/Users/fangwang/Downloads/P8105 Data Science I/p8105_hw3_fw2394/snowfall_common.png")
```

    ## Saving 6 x 3.6 in image
    ## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.

    ## Warning: Removed 381221 rows containing non-finite outside the scale range
    ## (`stat_bin()`).

*Based on the histogram, a value of 0 is the most commonly observed for
snowfall. This is expected in climates where snowfall primarily occurs
during winter. Even during winter, many regions and days experience no
snowfall, leading to a high accumulation of days with zero snowfall.
Consequently, 0 is the most frequently recorded value in the dataset.*

## Make a two-panel plot showing the average max temperature in January and in July in each station across years:

``` r
ave_tmax_station = ny_noaa |> 
  filter (month %in% c("01", "07")) |> 
  group_by(year, id, month) |> 
  summarise(avg_tmax = mean(tmax, na.rm = TRUE))
```

    ## `summarise()` has grouped output by 'year', 'id'. You can override using the
    ## `.groups` argument.

``` r
month = c("01" = "January", "07" = "July")
labeller_month = as_labeller(month)

ave_tmax_station |> 
  ggplot(aes(x = year, y= avg_tmax, color = month)) +
  geom_boxplot() +
  facet_wrap(~ month, labeller = labeller_month) +
  labs (
    title = "Average Max Temperature in January and July in Each Station Across Years",
    x = "Years",
    y = "Average Max Temperature (°C) in Each Station",
    color = "Month"
  ) +
  scale_color_discrete(labels = c("January", "July")) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1, size = 6)) + theme(axis.title.y = element_text(size = 7)) +
  theme(plot.title=element_text(size=11, face="bold"))+
  theme(plot.title = element_text(hjust = 0.5))
```

    ## Warning: Removed 5970 rows containing non-finite outside the scale range
    ## (`stat_boxplot()`).

<img src="p8105_hw3_fw2394_files/figure-gfm/unnamed-chunk-1-1.png" width="90%" />

``` r
ggsave("/Users/fangwang/Downloads/P8105 Data Science I/p8105_hw3_fw2394/tmax_station.png")
```

    ## Saving 6 x 3.6 in image

    ## Warning: Removed 5970 rows containing non-finite outside the scale range
    ## (`stat_boxplot()`).

*The plot shows a clear seasonal pattern in temperature, with expected
lower temperatures in January (left panel) and higher temperatures in
July (right panel). The average max temperature in January shows lower
values, mostly ranging between -10 and 10 degrees Celsius, as expected
for winter. The average max temperature in July is consistently higher,
mostly ranging between 20 and 30 degrees Celsius. There are some
outliers in the January panel, with temperatures dropping significantly
below -10°C. These might be due to extremely cold conditions at specific
stations or during particular years.The July panel also has some
outliers, with some temperatures falling below or above the main range.*

## Make a two-panel plot showing tmax vs tmin for the full dataset:

``` r
observations = c("tmax" = "Maximum Temperature", "tmin" = "Minimum Temperature")
labeller_observations = as_labeller(observations)

ny_noaa |> 
  pivot_longer(
    cols = tmax:tmin,
    names_to = "observations",
    values_to = "temperature"
  ) |> 
  ggplot (aes(x = year, y = temperature, fill = observations)) +
  geom_violin(alpha = 0.7) +
  stat_summary(fun = "median", geom = "point", size = 0.1) +
  facet_wrap(.~ observations, labeller = labeller_observations) +
  labs (
    title = "Maximum and Minimum Temperature Across Years",
    x = "Years",
    y = "Temperature (°C)",
    fill = "Observations"
  ) +
  scale_fill_discrete(labels = c("Maximum Temperature", "Minimum Temperature")) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1, size = 6)) +
  theme(plot.title=element_text(size=14, face="bold"))+
  theme(plot.title = element_text(hjust = 0.5))
```

    ## Warning: Removed 2268778 rows containing non-finite outside the scale range
    ## (`stat_ydensity()`).

    ## Warning: Removed 2268778 rows containing non-finite outside the scale range
    ## (`stat_summary()`).

<img src="p8105_hw3_fw2394_files/figure-gfm/unnamed-chunk-2-1.png" width="90%" />

``` r
ggsave("/Users/fangwang/Downloads/P8105 Data Science I/p8105_hw3_fw2394/tmax_tmin.png")
```

    ## Saving 6 x 3.6 in image

    ## Warning: Removed 2268778 rows containing non-finite outside the scale range
    ## (`stat_ydensity()`).
    ## Removed 2268778 rows containing non-finite outside the scale range
    ## (`stat_summary()`).

*The plot is a violin plot that shows the distribution of maximum and
minimum temperatures across the years 1981 to 2010. The x-axis
represents the years, and the y-axis represents the temperature in
degrees Celsius. The violin plots are colored red for maximum
temperature and blue for minimum temperature.The median maximum
temperature is generally higher than the median minimum temperature, as
we expected.*

## make a plot showing the distribution of snowfall values greater than 0 and less than 100 separately by year:

``` r
ny_noaa |> 
  filter (snow > 0, snow < 100) |> 
  ggplot(aes(x = snow)) +
  geom_histogram(fill = "orange", color = "black") +
  facet_wrap(. ~ year) +
  labs (
    title = "Snowfall Distribution by Year",
    x = "Snowfall (mm)",
    y = "Frequency"
  ) +
  theme(axis.text.x = element_text(hjust = 1, size = 6)) +
  theme(axis.text.y = element_text(size = 6)) +
  theme(plot.title=element_text(size=18, face="bold"))+
  theme(plot.title = element_text(hjust = 0.5))
```

    ## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.

<img src="p8105_hw3_fw2394_files/figure-gfm/snowfall-1.png" width="90%" />

``` r
ggsave ("/Users/fangwang/Downloads/P8105 Data Science I/p8105_hw3_fw2394/distribution of snowfall by years.png")
```

    ## Saving 6 x 3.6 in image
    ## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.

*This plot shows the distribution of snowfall values (between 0 and
approximately 100) across different years from 1981 to 2010. Each small
histogram represents a separate year. The x-axis shows snowfall values
and the y-axis displays the count of observations (frequency) in each
snowfall range. The histograms reveal that snowfall tends to cluster at
lower values, with most observations concentrated below 50mm, and the
frequency of higher than 75mm is relatively low across all years. The
distribution of snowfall appears to be fairly consistent year-to-year.*

# Problem 2

## Load data and merge data:

``` r
nhanes_covar = read_csv("/Users/fangwang/Downloads/P8105 Data Science I/p8105_hw3_fw2394/data/nhanes/nhanes_covar.csv", skip = 4) |> 
  janitor::clean_names() |> 
  mutate (
    sex = case_when(
    sex == 1 ~ "male",
    sex == 2 ~ "female"),
    education = case_when (
    education == 1 ~ "less than high school",
    education == 2 ~ "high school equivalent",
    education == 3 ~ "more than high school",
    ))
```

    ## Rows: 250 Columns: 5
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (5): SEQN, sex, age, BMI, education
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
nhanes_accel = read_csv("/Users/fangwang/Downloads/P8105 Data Science I/p8105_hw3_fw2394/data/nhanes/nhanes_accel.csv") |> 
  janitor::clean_names()
```

    ## Rows: 250 Columns: 1441
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (1441): SEQN, min1, min2, min3, min4, min5, min6, min7, min8, min9, min1...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
nhanes = left_join(nhanes_covar, nhanes_accel, by = "seqn") |> 
  drop_na () |> 
  filter(age >= 21)
```

*The final dataset “nhanes” includes 228 observations and 1445
variables.*

## Produce a reader-friendly table for the number of men and women in each education category, and create a visualization of the age distributions for men and women in each education category.

``` r
nhanes |> 
  group_by (sex, education) |> 
  summarise(total_number = n(), .groups = "drop") |> 
  pivot_wider(
    names_from = "education",
    values_from = "total_number"
  ) |> 
  knitr::kable(caption = "The Number of Men and Women in Each Education Category")
```

| sex    | high school equivalent | less than high school | more than high school |
|:-------|-----------------------:|----------------------:|----------------------:|
| female |                     23 |                    28 |                    59 |
| male   |                     35 |                    27 |                    56 |

The Number of Men and Women in Each Education Category

``` r
nhanes |> 
  mutate(education = fct_relevel(education, 
                                 c("less than high school", 
                                   "high school equivalent", 
                                   "more than high school"))) |>
  ggplot(aes(x = education , y = age, color = sex)) +
  geom_boxplot () +
  facet_wrap(. ~ sex) +
  labs (
    title = "The Age Distribution for Men and Women in Each Education Category",
    x = "Education",
    y = "Age (year-old)",
    color = "Sex"
  ) +
  scale_color_discrete(labels = c("Female", "Male")) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1))+
  theme(plot.title=element_text(size=11, face="bold"))+
  theme(plot.title = element_text(hjust = 0.5))
```

<img src="p8105_hw3_fw2394_files/figure-gfm/table-1.png" width="90%" />

``` r
ggsave ("age distribution by sex and education categories.png")
```

    ## Saving 6 x 3.6 in image

*This boxplot visualizes the age distribution of men and women across
three education levels: “less than high school,” “high school
equivalent,” and “more than high school.” The plot is split by gender,
with females on the left (red) and males on the right (blue). For each
education level, the boxes represent the interquartile range (IQR),
showing the middle 50% of the age distribution, with the horizontal line
inside each box indicating the median age. The whiskers extend to the
minimum and maximum ages, excluding outliers. The median age tends to be
higher for individuals with lower educational attainment, especially in
the “less than high school” category for both genders. Men and women
show similar age distributions within “less than high school” and “more
than high school” education levels. However, in the “high school
equivalent” category, women have a slightly higher median age than men.*

## Plot these total activities (y-axis) against age (x-axis); your plot should compare men to women and have separate panels for each education level:

``` r
nhanes = nhanes |> 
  mutate (total_activity = rowSums(across(min1:min1440), na.rm = TRUE))

nhanes |> 
  mutate(education = fct_relevel(education, 
                                 c("less than high school", 
                                   "high school equivalent", 
                                   "more than high school"))) |> 
  ggplot (aes (x = age, y = total_activity, color = sex)) +
  geom_point() +
  geom_smooth (method = "lm", se = FALSE) +
  facet_wrap(. ~ education) +
  labs (
    title = "Comparison of Total Activity between Men and Women for Different Education Levels",
    x = "Age (year-old)",
    y = "Total Activity",
    color = "Sex"
  ) +
  scale_color_discrete(labels = c("Female", "Male")) +
  theme(axis.text.x = element_text(hjust = 1)) +
  theme(plot.title=element_text(size=9, face="bold"))+
  theme(plot.title = element_text(hjust = 0.5))
```

    ## `geom_smooth()` using formula = 'y ~ x'

<img src="p8105_hw3_fw2394_files/figure-gfm/unnamed-chunk-3-1.png" width="90%" />

``` r
ggsave ("total activity by sex and education levels.png")
```

    ## Saving 6 x 3.6 in image
    ## `geom_smooth()` using formula = 'y ~ x'

*In all educational categories, both men and women show a negative
relationship between age and total activity, with activity levels
generally decreasing as age increases, particularly for individuals with
lower education levels. This trend is indicated by the downward-sloping
lines of for both genders.*

## Make a three-panel plot that shows the 24-hour activity time courses for each education level and use color to indicate sex.

``` r
nhanes_longer = nhanes|> 
  pivot_longer(
    cols = min1: min1440,
    names_to = "minute",
    values_to = "activity",
    names_prefix = "min"
  )

nhanes_longer |> 
  ggplot(aes(x = as.numeric(minute)/60, y = activity, color = sex))+
  geom_point(alpha = .2, size = .2) +
  geom_smooth(se = FALSE, size = 1.2) +
  facet_wrap(. ~ education) +
  scale_x_continuous(breaks = seq(0, 24, by = 1),
                     labels = seq(0, 24, by = 1)) +
  labs (
    title = "24-hour Activity for Men and Women in Each Education Level",
    x = "Hours",
    y = "Activity",
    color = "Sex"
  ) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 5)) +
  theme(plot.title=element_text(size=13, face="bold"))+
  theme(plot.title = element_text(hjust = 0.5))
```

    ## Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
    ## ℹ Please use `linewidth` instead.
    ## This warning is displayed once every 8 hours.
    ## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
    ## generated.

    ## `geom_smooth()` using method = 'gam' and formula = 'y ~ s(x, bs = "cs")'

<img src="p8105_hw3_fw2394_files/figure-gfm/unnamed-chunk-4-1.png" width="90%" />

``` r
ggsave ("/Users/fangwang/Downloads/P8105 Data Science I/p8105_hw3_fw2394/24-hour activity by sex and education levels.png")
```

    ## Saving 6 x 3.6 in image
    ## `geom_smooth()` using method = 'gam' and formula = 'y ~ s(x, bs = "cs")'

*There are noticeable clusters of high activity from 8:00am to 20:00pm,
indicating times when most participants were more active. The activity
levels generally remain below 50, with few extreme values reaching close
to 100 in the “more than high school” educational level.There is no
significant visible difference in activity between males and females
based on trend lines.*

# Problem 3

## Load data

``` r
jan_2020 = read_csv("./data/citibike/Jan 2020 Citi.csv") |> 
  mutate (year = "2020", month = "January")
```

    ## Rows: 12420 Columns: 7
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (6): ride_id, rideable_type, weekdays, start_station_name, end_station_n...
    ## dbl (1): duration
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
jan_2024 = read_csv("./data/citibike/Jan 2024 Citi.csv") |> 
  mutate (year = "2024", month = "January")
```

    ## Rows: 18861 Columns: 7
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (6): ride_id, rideable_type, weekdays, start_station_name, end_station_n...
    ## dbl (1): duration
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
july_2020 = read_csv("./data/citibike/July 2020 Citi.csv") |> 
  mutate (year = "2020", month = "July")
```

    ## Rows: 21048 Columns: 7
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (6): ride_id, rideable_type, weekdays, start_station_name, end_station_n...
    ## dbl (1): duration
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
july_2024 = read_csv("./data/citibike/July 2024 Citi.csv") |> 
  mutate (year = "2024", month = "July")
```

    ## Rows: 47156 Columns: 7
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (6): ride_id, rideable_type, weekdays, start_station_name, end_station_n...
    ## dbl (1): duration
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

## Produce a reader-friendly table showing the total number of rides in each combination of year and month separating casual riders and Citi Bike members:

``` r
citibike = rbind (jan_2020, july_2020, jan_2024, july_2024)

citibike |> 
  group_by (year, month, member_casual) |> 
  summarise(total_rides = n(), .groups = "drop") |> 
  pivot_wider(
    names_from = "member_casual",
    values_from = "total_rides"
  ) |> 
  knitr::kable()
```

| year | month   | casual | member |
|:-----|:--------|-------:|-------:|
| 2020 | January |    984 |  11436 |
| 2020 | July    |   5637 |  15411 |
| 2024 | January |   2108 |  16753 |
| 2024 | July    |  10894 |  36262 |

*This table shows the number of “casual” and “member” users for two
different years (2020 and 2024) in the months of January and July. From
2020 to 2024, there is a significant increase in both casual and member
users in both months. The data suggests that the number of users is
higher in July compared to January in both years. Member users
consistently outnumber casual users in all periods. For instance, in
July 2024, member users were 36,262, while casual users were 10,894.*

## Make a table showing the 5 most popular starting stations for July 2024; include the number of rides originating from these stations.

``` r
july_2024 |> 
  group_by(start_station_name) |> 
  summarise(num_rides = n(), .groups = "drop") |> 
  arrange(desc(num_rides)) |> 
  head (5)|> 
  knitr::kable(
    col.names =c("Start Station Names", "Number of Rides") ,
    caption = "The 5 Most Popular Starting Stations for July 2024")
```

| Start Station Names      | Number of Rides |
|:-------------------------|----------------:|
| Pier 61 at Chelsea Piers |             163 |
| University Pl & E 14 St  |             155 |
| W 21 St & 6 Ave          |             152 |
| West St & Chambers St    |             150 |
| W 31 St & 7 Ave          |             146 |

The 5 Most Popular Starting Stations for July 2024

*This table lists the five most popular starting stations for bike rides
in July 2024, along with the number of rides originating from each
station. “Start Station Names” represents the name of the bike station
where rides started. “Number of Rides” represents the total number of
rides that originated from each respective station.*

## Make a plot to investigate the effects of day of the week, month, and year on median ride duration. This plot can include one or more panels, but should facilitate comparison across all variables of interest. Comment on your observations from this plot

``` r
median_duration_day = citibike |> 
  group_by (weekdays) |> 
  summarise (median_duration_day = median(duration)) |> 
  mutate(weekdays = fct_relevel(weekdays, 
                                c("Monday", 
                                  "Tuesday", 
                                  "Wednesday", 
                                  "Thursday", 
                                  "Friday", 
                                  "Saturday", 
                                  "Sunday")),
         weekdays_num = as.numeric(weekdays)) 

median_duration_month = citibike |> 
  group_by (month) |> 
  summarise (median_duration_month = median(duration)) |> 
  mutate(month = fct_relevel(month, 
                                c("January", 
                                  "July")),
         month_num = as.numeric(month)) 

median_duration_year = citibike |> 
  group_by (year) |> 
  summarise (median_duration_year = median(duration))|> 
  mutate(year = fct_relevel(year, 
                            c("2020", 
                              "2024")),
         year_num = as.numeric(year)) 

plot_day = median_duration_day |> 
  ggplot (aes(x = weekdays_num, y = median_duration_day)) +
  geom_point() +
  geom_smooth (method = "lm", se = FALSE) +
  scale_x_continuous(breaks = 1:7, labels = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday")) +
  labs(
    title = "The Effects of Weekdays on Median Ride Duration",
    x = "Day of the Week",
    y = "Median Ride Duration (hours)"
  ) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1)) +
  theme(plot.title=element_text(size=5, face="bold"))+
  theme(plot.title = element_text(hjust = 0.5))
  
plot_month = median_duration_month |> 
  ggplot (aes(x = month_num, y = median_duration_month)) +
  geom_point() +
  geom_smooth (method = "lm", se = FALSE) +
  scale_x_continuous(breaks = 1:2, labels = c("January", "July")) +
  labs(
    title = "The Effects of Months on Median Ride Duration",
    x = "Months",
    y = "Median Ride Duration (hours)"
  ) +
  theme(axis.text.x = element_text(hjust = 1)) +
  theme(plot.title=element_text(size=5, face="bold"))+
  theme(plot.title = element_text(hjust = 0.5))

plot_year = median_duration_year |> 
  ggplot (aes(x = year_num, y = median_duration_year)) +
  geom_point() +
  geom_smooth (method = "lm", se = FALSE) +
  scale_x_continuous(breaks = 1:2, labels = c("2020", "2024")) +
  labs(
    title = "The Effects of Years on Median Ride Duration",
    x = "Years",
    y = "Median Ride Duration (hours)"
  ) +
  theme(axis.text.x = element_text(hjust = 1)) +
  theme(plot.title=element_text(size=5, face="bold"))+
  theme(plot.title = element_text(hjust = 0.5))

plot_day + plot_month + plot_year
```

    ## `geom_smooth()` using formula = 'y ~ x'
    ## `geom_smooth()` using formula = 'y ~ x'
    ## `geom_smooth()` using formula = 'y ~ x'

<img src="p8105_hw3_fw2394_files/figure-gfm/unnamed-chunk-7-1.png" width="90%" />

``` r
ggsave("/Users/fangwang/Downloads/P8105 Data Science I/p8105_hw3_fw2394/plot_combination.png")
```

    ## Saving 6 x 3.6 in image
    ## `geom_smooth()` using formula = 'y ~ x'
    ## `geom_smooth()` using formula = 'y ~ x'
    ## `geom_smooth()` using formula = 'y ~ x'

*This shows three plots that illustrate the effects of weekdays, months,
and years on median ride duration. The top plot shows the Effects of
Weekdays on Median Ride Duration. The x-axis represents the day of the
week (Monday to Sunday). The y-axis shows the median ride duration in
hours. There is a general increasing trend in median ride duration from
Monday to Sunday. The ride duration appears to be shortest on Monday
(just above 9 hours) and longest on Sunday (around 11 hours). The blue
linear trend line shows a steady increase in ride duration across the
weekdays, indicating that ride durations tend to increase as the week
progresses. The bottom-left plot shows the effects of months on median
ride duration. The x-axis represents the month (January and July). The
median ride duration is higher in July compared to January. The duration
increases between January and July, which may suggest that people tend
to take longer rides during the period. The blue line shows a positive
trend from January to July, indicating a seasonal effect on ride
duration. The bottom-right plot shows the effects of years on median
ride duration. The x-axis represents the year (2020 and 2024). There is
a decrease in median ride duration from 2020 to 2024, with the duration
dropping from 12 hours to around 9 hours. The blue trend line is
downward, indicating that over time, the median ride duration has
decreased.*

## For data in 2024, make a figure that shows the impact of month, membership status, and bike type on the distribution of ride duration.

``` r
citibike_2024 = rbind (jan_2024, july_2024)

citibike_table = citibike_2024 |> 
  group_by (month, rideable_type, member_casual) |>   
  summarise (ride_duration = median(duration, na.rm = TRUE), .groups = "drop") |> 
  mutate(month_num = case_when(
    month == "January" ~ 1,
    month == "July" ~ 2,
    TRUE ~ NA_real_
  ))

citibike_table |>  
  ggplot (aes(x = month_num, y = ride_duration, color = rideable_type)) + 
  geom_point() +
  geom_smooth (method= "lm", se = FALSE) +
  facet_wrap(.~ member_casual) +
  scale_x_continuous(breaks = 1:2, labels = c("January", "July")) +
  labs(
    title = "The Effects of Months in 2024 on Median Ride Duration",
    x = "Months in 2024",
    y = "Median Ride Duration (hours)",
    color = "Type of Bike"
  ) +
  scale_color_discrete(labels = c("Class Bike", "Electric Bike")) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1)) +
  theme(plot.title=element_text(size=14, face="bold"))+
  theme(plot.title = element_text(hjust = 0.5))
```

    ## `geom_smooth()` using formula = 'y ~ x'

<img src="p8105_hw3_fw2394_files/figure-gfm/unnamed-chunk-8-1.png" width="90%" />

``` r
ggsave ("/Users/fangwang/Downloads/P8105 Data Science I/p8105_hw3_fw2394/effect of months on median ride duration.png")
```

    ## Saving 6 x 3.6 in image
    ## `geom_smooth()` using formula = 'y ~ x'

*The plot shows the effects of months in 2024 on median ride duration
for casual and member users, distinguishing between class bikes and
electric bikes. In both casual and member user panels, there is an
observable increase in median ride duration from January to July,
indicating a seasonal effect where ride durations are longer in
summer.Casual users have a generally higher ride duration compared to
member users for both types of bikes. Class Bikes (red line) have higher
median ride durations for casual users (left panel) compared to Electric
Bikes in both months, indicating that casual users may prefer class
bikes. For member users (right panel), electric bikes have a higher ride
duration compared to class bikes, showing a preference for electric
bikes among members. Electric Bikes (blue line) exhibit a significant
increase in ride duration from January to July for both casual and
member users, reflecting their growing popularity.*
